version: '3'
services:

  logoclassifier-service:
    image: docker.uncharted.software/logoclassifier:latest
    ports:
      - 5001
    env_file: .env
    networks:
      bringmehome:
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1G

  bringmehome:
    image: docker.uncharted.software/bringmehome:latest
    ports:
      - 80:3010
    links:
      - logoclassifier-service
    depends_on:
      - logoclassifier-service
    env_file: .env
    networks:
      bringmehome:
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1G

networks:
  bringmehome:
