version: '3'
services:
  bringmehome:
    image: docker.uncharted.software/bringmehome:latest
    ports:
      - 3010:3010
    env_file: .env
    networks:
      bringmehome:
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1G

networks:
  bringmehome:
