# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
          version: 17.05.0-ce

      - run:
          name: Build Docker image
          command: |
            TAG="1.0.${CIRCLE_BUILD_NUM}"
            docker build -t docker.uncharted.software/bringmehome:$TAG .
            docker build -t docker.uncharted.software/bringmehome:latest .

      - deploy:
          name: Push Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" != "master" ]; then
              TAG="1.0.${CIRCLE_BUILD_NUM}"
              docker login docker.uncharted.software -u${DOCKER_USER} -p${DOCKER_PASS}
              docker push docker.uncharted.software/bringmehome:$TAG
              docker push docker.uncharted.software/bringmehome:latest;
            fi

      - add_ssh_keys:
          fingerprints:
            - "15:35:c9:04:c5:eb:65:11:53:af:66:0f:6c:22:9c:36"

      - deploy:
          name: Deploy to Swarm
          command: |
            if [ "${CIRCLE_BRANCH}" != "master" ]; then
              scp ~/repo/docker-compose.yml core@${SWARM_ADDRESS}:/tmp/${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BUILD_NUM}-docker-compose.yml
              ssh core@${SWARM_ADDRESS} 'bash -s' < ~/repo/deploy/swarm_deploy.sh ${DOCKER_USER} ${DOCKER_PASS} ${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BUILD_NUM} ${CIRCLE_PROJECT_REPONAME};
            fi
