# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

  deploy:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - setup_remote_docker:
          version: 17.05.0-ce

      - run:
          name: Build Docker image
          command: |
            TAG="1.0.${CIRCLE_BUILD_NUM}"
            docker build -t docker.uncharted.software/bringmehome:$TAG .
            docker login docker.uncharted.software -u ${DOCKER_USER} -p ${DOCKER_PASS}
            # scp ~/repo/docker-compose.yml core@${SWARM_ADDRESS}:/tmp/${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BUILD_NUM}-docker-compose.yml
            # ssh core@${SWARM_ADDRESS} 'bash -s' < ~/repo/deploy/swarm_deploy.sh ${DOCKER_USER} ${DOCKER_PASS} ${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BUILD_NUM} ${CIRCLE_PROJECT_REPONAME}

workflows:
  version: 2
  build_test:
    jobs:
      - build
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
